---
# task/cni_install for hashicorp_nomad
- name: "Create cni directory"
  ansible.builtin.file:
    path: "{{ hashi_nomad_cni_plugins_install_path }}"
    state: directory
    mode: "0775"

- name: "Install cni plugins version:{{ hashi_nomad_cni_plugins_version }}"
  ansible.builtin.get_url:
    url: "{{ hashi_nomad_cni_plugins_download_url }}"
    dest: "/tmp/cni_plugin.tgz"
    mode: "0644"
  register: _cni_plugins_download_archive
  until: _cni_plugins_download_archive is succeeded
  retries: 5
  delay: 2
  check_mode: false

- name: "Unpack cni plugins"
  ansible.builtin.unarchive:
    src: "/tmp/cni_plugin.tgz"
    dest: "{{ hashi_nomad_cni_plugins_install_path }}"
    remote_src: true

- name: "Update version file"
  ansible.builtin.copy:
    content: "{{ hashi_nomad_cni_plugins_version }}"
    dest: "{{ hashi_nomad_cni_plugins_install_path }}/version"
    mode: "0600"
