---
# task/configure file for hashicorp_nomad
- name: "Copy nomad.hcl template"
  ansible.builtin.template:
    src: nomad.hcl.j2
    dest: /etc/nomad.d/nomad.hcl
    owner: nomad
    group: nomad
    mode: '0600'
  notify: "systemctl-enable-nomad"

- name: "Create empty nomad.env"
  ansible.builtin.file:
    path: "/etc/nomad.d/nomad.env"
    owner: nomad
    group: nomad
    mode: '0600'
    state: file