---
# task/configure file for hashicorp_nomad
- name: "Copy nomad.hcl template"
  ansible.builtin.template:
    src: nomad.hcl.j2
    dest: "{{ hashi_nomad_config_dir }}/nomad.hcl"
    owner: "{{ hashi_nomad_user }}"
    group: "{{ hashi_nomad_group }}"
    mode: '0600'
  notify:
    - "systemctl-enable-nomad"
    - "systemctl-restart-nomad"

- name: "Create empty nomad.env"
  ansible.builtin.file:
    path: "{{ hashi_nomad_config_dir }}/nomad.env"
    owner: "{{ hashi_nomad_user }}"
    group: "{{ hashi_nomad_group }}"
    mode: '0600'
    state: file
