---
# task/install file for hashicorp_nomad
- name: "Configure hashicorp repository"
  ansible.builtin.include_role:
    name: ednxzu.manage_repositories
  vars:
    manage_repositories_enable_default_repo: false
    manage_repositories_enable_custom_repo: true
    manage_repositories_custom_repo:
      - uri: "https://apt.releases.hashicorp.com"
        gpg_key: "https://apt.releases.hashicorp.com/gpg"
        comments: "hashicorp repository"
        type: "deb"
        suites: "{{ ansible_distribution_release }}"
        components: "main"
        filename: "hashicorp"

- name: "Install nomad:{{ hashi_nomad_version }}"
  ansible.builtin.include_role:
    name: ednxzu.manage_apt_packages
  vars:
    manage_apt_packages_list:
      - name: nomad
        version: "{{ hashi_nomad_version }}"
        state: present

- name: "Copy systemd service file for nomad"
  ansible.builtin.copy:
    src: "files/nomad.service"
    dest: "/lib/systemd/system/nomad.service"
    owner: root
    group: root
    mode: '0644'
    force: false
