---
# tasks file for hashicorp_nomad
- name: "Import prerequisites.yml"
  ansible.builtin.include_tasks: prerequisites.yml

- name: "Import install.yml"
  ansible.builtin.include_tasks: install.yml
  when: hashi_nomad_install

- name: "Import CNI related tasks"
  when: hashi_nomad_cni_plugins_install
  block:
    - name: "Import cni_prerequisites.yml"
      ansible.builtin.include_tasks: cni_prerequisites.yml

    - name: "Import cni_install.yml"
      ansible.builtin.include_tasks: cni_install.yml

- name: "Import configure.yml"
  ansible.builtin.include_tasks: configure.yml
