---
hashi_nomad_install: true
hashi_nomad_cni_plugins_install: true
hashi_nomad_start_service: true
hashi_nomad_cni_plugins_version: "1.2.0"
hashi_nomad_cni_plugins_install_path: "/opt/cni/bin"
hashi_nomad_version: latest
hashi_nomad_deploy_method: host  # deployment method, either host or docker
hashi_nomad_datacenter: dc1
hashi_nomad_data_dir: /opt/nomad
hashi_nomad_bind_addr: "0.0.0.0"
hashi_nomad_advertise_addr:
  http: "{{ ansible_default_ipv4.address }}"
  rpc: "{{ ansible_default_ipv4.address }}"
  serf: "{{ ansible_default_ipv4.address }}"
hashi_nomad_log_level: INFO
hashi_nomad_leave_on_terminate: false
# nomad server
hashi_nomad_server_enabled: true
hashi_nomad_server:
  ui: true
  bootstrap_expect: 1
  retry_join:
    - "{{ ansible_default_ipv4.address }}"
# nomad client
hashi_nomad_client_enabled: false
hashi_nomad_client:
  node_class: default
  reserved_cpu: 500
  reserved_memory: 300
  cni_path: "{{ hashi_nomad_cni_plugins_install_path }}"
  bridge_network_name: nomad
  bridge_network_subnet: "172.26.64.0/20"
# nomad acl
hashi_nomad_acl_enabled: true
hashi_nomad_acl:
  token_ttl: 30s
  policy_ttl: 30s
  role_ttl: 30s
  token_min_expiration_ttl: 1m
  token_max_expiration_ttl: 24h
# nomad telemetry
hashi_nomad_telemetry_enabled: false
hashi_nomad_telemetry:
  collection_interval: 1s
  disable_hostname: false
  use_node_name: false
  publish_allocation_metrics: false
  publish_node_metrics: false
  prefix_filter: false
  disable_dispatched_job_summary_metrics: []
  prometheus_metrics: false
# nomad consul registration
hashi_nomad_consul_enabled: false
hashi_nomad_consul:
  ui: http://consul.service.consul/
  address: "127.0.0.1:8500"
  token: ""
  auto_advertise: true
# nomad vault registration
hashi_nomad_vault_enabled: false
hashi_nomad_vault:
  ui: http://vault.service.consul/
  address: http://vault.service.consul:8200
  token: ""
  tls_skip_verify: true
  create_from_role: nomad-cluster
# nomad docker driver
hashi_nomad_docker_driver_enabled: false
hashi_nomad_docker_driver:
  endpoint: "unix:///var/run/docker.sock"
  allow_privileged: false
  allow_caps: ["all"]
  volumes_enabled: true
